name: simple CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
